name: Upload Graph to LINDAS

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.12"
          enable-caching: true

      - name: Install system dependencies
        run: sudo apt-get install -y libssh2-1-dev

      - name: Install dependencies
        run: uv sync

      - name: Run pipeline script
        run: uv run python service/pipeline.py

      - name: Upload to LINDAS
        env:
          LINDAS_USER: ${{ secrets.LINDAS_USER }}
          LINDAS_PASSWORD: ${{ secrets.LINDAS_PASSWORD }}
          ENDPOINT: ${{ secrets.ENDPOINT }}
          GRAPH: ${{ secrets.GRAPH }}
        run: uv run python service/upload_graph.py
